image: node:10-alpine

variables:
  LC_ALL: C.UTF-8
  DOCKER_DRIVER: overlay2

before_script:
  - yarn install

stages:
- test
- build
- deploy

jest:
  stage: test
  script:
  - yarn run jest
  cache:
    paths:
      - node_modules/

tslint:
  stage: test
  script:
  - yarn run lint
  cache:
    paths:
      - node_modules/

rollup:
  stage: build
  script:
  - yarn run build
  cache:
    paths:
      - node_modules/

pages:
  stage: deploy
  script:
  - yarn run generateDocs
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules/
