#!/usr/local/bin/node

const argue = require("./lib/lib");

console.log(argue.options([{"verbose":"v"},{"save":"s"}], [{"output":"o"}]));
console.log(argue.expect({"install":"i"}, "remove"));
console.log(argue.read());
argue.end();

// process.exit();